config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get '/employer' => "employers#index", as: :user_root
  get 'display/index'
  root 'display#index'

  resources :employers do
    resources :employees, :budgets
  end
  
  resources :employees do
    resources :timesheets
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :employer
  has_many :timesheets, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :get_employer
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = @employer.employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
  end

  # GET /employees/new
  def new
    @employee = @employer.employees.build
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = @employer.employees.build(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employer_employees_path(@employer), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employer_employees_path(@employer), notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employer_employees_path(@employer), notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_employer
      @employer = Employer.find(params[:employer_id])
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = @employer.employees.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :employer_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: [@employer, employee], local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h3>Editing Employee</h3>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', [@employer, @employee], class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', employer_employees_path(@employer), class: "btn btn-outline-secondary" %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h3>
  Employer: <%= link_to @employer.name, employer_path(@employer) %>
</h3>

<h3>Employees</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.name, [@employer, employee] %></td>
        
        
        <td><%= link_to 'Edit Employee', edit_employer_employee_path(@employer, employee) %></td>
        <td><%= link_to 'Destroy Employee', [@employer, employee], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Employee', new_employer_employee_path(@employer), class: "btn btn-outline-secondary" %>

app/views/employees/new.html.erb
<h3>New Employee</h3>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employer_employees_path(@employer), class: "btn btn-outline-secondary" %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
 Employer: <%= link_to @employee.employer.name, [@employer] %>
</h3>

<h3>
 Employee: <%= @employee.name %>
</h3>

<h3><%= link_to 'Timesheets', employee_timesheets_path(@employee) %></h3>
<% for timesheet in @employee.timesheets %>
   <ul>
     <li><%= link_to timesheet.name, [@employee, timesheet] %></li>
   </ul>
<% end %>

<%= link_to "Edit Employee", edit_employer_employee_path, class: "btn btn-outline-secondary" %>
<%= link_to "Add Timesheet", new_employee_timesheet_path(@employee), class: "btn btn-outline-secondary" %>