config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get '/employer' => "employers#index", as: :user_root
  get 'display/index'
  root 'display#index'

  resources :employers do
    resources :employees, :budgets
  end
  
  resources :employees do
    resources :timesheets
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
  
  
  
  belongs_to :employer
  has_many :timesheets
  validates :name, presence: true, uniqueness: true
  validates :hours, presence: true
  validate :end_after_start
  validates :start_date, :end_date, presence: true
 
  
  private
  def end_after_start
    return if end_date.blank? || start_date.blank?
    
    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
  
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :get_employer
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = @employer.budgets
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @budget = Budget.find(params[:id])
  end

  # GET /budgets/new
  def new
    @budget = @employer.budgets.build
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = @employer.budgets.build(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to employer_budgets_path(@employer), notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to employer_budget_path(@employer), notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to employer_budgets_path(@employer), notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_employer
      @employer = Employer.find(params[:employer_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = @employer.budgets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:name, :hours, :start_date, :end_date, :employer_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: [@employer, budget], local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :budget_name %>
  </div>

  <div class="field">
    <%= form.label :hours %>
    <%= form.number_field :hours, id: :budget_hours %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :budget_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :budget_end_date %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h3>Editing Budget</h3>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', [@employer, @budget], class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', employer_budget_path(@employer), class: "btn btn-outline-secondary" %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h3>
  Employer: <%= link_to @employer.name, employer_path(@employer) %>
</h3>

<h3>Budgets</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= link_to budget.name, [@employer, budget] %></td>
        <td><%= budget.hours %></td>
        <td><%= budget.start_date %></td>
        <td><%= budget.end_date %></td>
        <td><%= link_to 'Edit Budget', edit_employer_budget_path(@employer, budget) %></td>
        <td><%= link_to 'Destroy Budget', [@employer, budget], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Budget',new_employer_budget_path(@employer), class: "btn btn-outline-secondary"  %>

app/views/budgets/new.html.erb
<h3>New Budget</h3>

<%= render 'form', budget: @budget %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Employer:</strong>
  <%= link_to @budget.employer.name, [@employer] %>
</h3>

<h3>
  <strong>Budget:</strong>
  <%= @budget.name %>
</h3>

 

<p>
  <strong>Hours:</strong>
  <%= @budget.hours %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @budget.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @budget.end_date %>
</p>

<%= link_to 'Edit Budget', edit_employer_budget_path(@employer, @budget), class: "btn btn-outline-secondary" %>
<%= link_to 'Back', employer_budgets_path(@employer), class: "btn btn-outline-secondary"  %>