config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get '/employer' => "employers#index", as: :user_root
  get 'display/index'
  root 'display#index'

  resources :employers do
    resources :employees, :budgets
  end
  
  resources :employees do
    resources :timesheets
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
  belongs_to :employee
  belongs_to :budget
  validates :name, presence: true, uniqueness: true
  validates :service_hours, presence: true
  validates :date_of_service, presence: true 
  validates :budget_id, presence: true, numericality: { only_integer: true }
  validate :within_budget_id_date_span
  
  validate :budget_id_hours_left
  
  private
  
  def within_budget_id_date_span
     if date_of_service < budget.start_date || date_of_service > budget.end_date
       errors.add(:Timesheet, "Date of service must be within the Budget date span!")
     end
  end
  
 
  
  def budget_id_hours_left
    if budget.timesheets.sum(&:service_hours) + service_hours > budget.hours
      errors.add(:Timesheet, "Not enough hours left in the Budget!")
    end
  end
  
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :get_employee
  before_action :set_timesheet, only: [:show, :edit, :update, :destroy]

  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = @employee.timesheets
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
  end

  # GET /timesheets/new
  def new
    @timesheet = @employee.timesheets.build
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets
  # POST /timesheets.json
  def create
    @timesheet = @employee.timesheets.build(timesheet_params)

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to employee_timesheets_path(@employee), notice: 'Timesheet was successfully created.' }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1
  # PATCH/PUT /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to employee_timesheet_path(@employee), notice: 'Timesheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to employee_timesheets_path(@employee), notice: 'Timesheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_employee
      @employee = Employee.find(params[:employee_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = @employee.timesheets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timesheet_params
      params.require(:timesheet).permit(:name, :service_hours, :date_of_service, :employee_id, :budget_id)
    end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= form_with(model: [@employee, timesheet], local: true) do |form| %>
  <% if timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% timesheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
  <strong>Employee:</strong>
  <%= @timesheet.employee.name %>
</p>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :timesheet_name %>
  </div>

  <div class="field">
    <%= form.label :service_hours %>
    <%= form.number_field :service_hours, id: :timesheet_service_hours %>
  </div>

  <div class="field">
    <%= form.label :date_of_service %>
    <%= form.date_select :date_of_service, id: :timesheet_date_of_service %>
  </div>
  
  <div class="control-group">
    <%= form.label :budget_id, class: 'control-label' %>
    <div class="controls">
       <%= collection_select( :timesheet, :budget_id, Budget.all, :id, :name, {}, { :multiple => false } ) %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h3>Editing Timesheet</h3>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Show', [@employee, @timesheet], class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', employee_timesheets_path(@employee), class: "btn btn-outline-secondary" %>

app/views/timesheets/index.html.erb
<p id="notice"><%= notice %></p>

<h3>
  Employee: 
</h3>

<h3>Timesheets</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Service hours</th>
      <th>Date of service</th>
      <th>Budget id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= link_to timesheet.name, [@employee, timesheet] %></td>
        <td><%= timesheet.service_hours %></td>
        <td><%= timesheet.date_of_service %></td>
        <td><%= timesheet.budget_id %></td>
        <td><%= link_to 'Edit Timesheet', edit_employee_timesheet_path(@employee, timesheet) %></td>
        <td><%= link_to 'Destroy Timesheet', [@employee, timesheet], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Timesheet', new_employee_timesheet_path(@employee), class: "btn btn-outline-secondary" %>

app/views/timesheets/new.html.erb
<h3>New Timesheet</h3>

<%= render 'form', timesheet: @timesheet %>

<%= link_to 'Back', employee_timesheets_path(@employee), class: "btn btn-outline-secondary" %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Timesheet:</strong>
  <%= @timesheet.name %>
</h3>

<h3>
  <strong>Employee:</strong>
  <%= link_to @timesheet.employee.name, [@employee] %>
</h3>

<p>
  <strong>Hours:</strong>
  <%= @timesheet.service_hours %>
</p>

<p>
  <strong>Date of service:</strong>
  <%= @timesheet.date_of_service %>
</p>

<p>
  <strong>Budget id:</strong>
  <%= @timesheet.budget_id %>
</p>

<%= link_to 'Edit Timesheet', edit_employee_timesheet_path,  class: "btn btn-outline-secondary" %>
<%= link_to 'Back', employee_timesheets_path(@employee), class: "btn btn-outline-secondary"  %>