config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  get '/employer' => "employers#index", as: :user_root
  get 'display/index'
  root 'display#index'

  resources :employers do
    resources :employees, :budgets
  end
  
  resources :employees do
    resources :timesheets
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :budgets, dependent: :destroy
  has_many :employees , dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
    @employer = Employer.find(params[:id])
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_with(model: employer, local: true) do |form| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employer_name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h3>Editing Employer</h3>

<%= render 'form', employer: @employer %>

<%= link_to 'Show', @employer, class: "btn btn-outline-secondary" %> 
<%= link_to 'Back', employers_path, class: "btn btn-outline-secondary" %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Employers</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= link_to employer.name, employer %></td>
        <td><%= link_to 'Edit Employer', edit_employer_path(employer) %></td> 
        <td><%= link_to 'Destroy Employer', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ Employer', new_employer_path, class: "btn btn-outline-secondary" %>

app/views/employers/new.html.erb
<h3>New Employer</h3>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path, class: "btn btn-outline-secondary" %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
 Employer: <%= @employer.name %>
 
</h3>


<h3>
  <%= link_to 'Employees', employer_employees_path(@employer) %>
  
</h3>
<% for employee in @employer.employees %>
  <ul>
    <li><%= link_to employee.name, [@employer, employee] %></li>
  </ul>
<% end %>

<h3>
  <%= link_to 'Budgets', employer_budgets_path(@employer) %>
  
</h3>
<% for budget in @employer.budgets %>
   <ul>
     <li><%=link_to budget.name, [@employer, budget] %></li>
   </ul>
<% end %>

<%= link_to 'Edit Employer', edit_employer_path(@employer), class: "btn btn-outline-secondary" %>
<%= link_to 'Add Employee', new_employer_employee_path(@employer), class: "btn btn-outline-secondary" %>
<%= link_to 'Add Budget', new_employer_budget_path(@employer), class: "btn btn-outline-secondary" %>
 